### ISSUE TITLE
unexpected error error="undefined method `to_h' for #<Array:0x000000033fbe90>"

### ISSUE THREAD

**Issue by alexwbaule** [codeout/fluent-plugin-netflow-multiplier#1]
If the version of Ruby is  < 2.1, the to_h dont exist.

**Comment by codeout** [comment]
Thank you for reporting, but ruby 2.0.x has been EoL'ed.
https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/

Do you really want to use old versions? I think I can push another branch to support them.

**Comment by alexwbaule** [comment]
Depending on the version and Distro that people use, it may be that the 2.0.x update to newer versions, has some late. When it comes to Ubuntu then, things always take time.

**Comment by codeout** [comment]
Published a new version fluent-plugin-netflow-multiplier 0.1.1 to fix this issue.
